// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Nastaliq_Urdu } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { EPDSProvider } from "../_context/EPDSResult";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Initialize Noto Nastaliq Urdu
const notoUrdu = Noto_Nastaliq_Urdu({
  variable: "--font-noto-urdu",
  subsets: ["arabic"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "EZCounselling EPDS",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoUrdu.variable} antialiased`}
      >
        <main className="w-full max-w-full mx-auto bg-white lg:[zoom:0.8]">
          <EPDSProvider>
            <div className="min-h-screen">
              <Navbar />

              {children}
            </div>
          </EPDSProvider>
        </main>
      </body>
    </html>
  );
}